version: '3.8'
services:
  backend:
    image: app_d
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - db
    networks:
      - rabbits

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_d
    command: python consumer.py
    depends_on:
      - rabbitmq
      - db
    networks:
      - rabbits

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - rabbits

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbit-1
    ports:
      - 5672:5672
      - 8080:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbits

networks:
  rabbits:
    driver: bridge
