version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - 8001:8000
    volumes:
      - .:/app
    depends_on:
      - fast-db
    networks:
      - rabbits

  queue_f:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_f
    command: python -u consumer.py
    depends_on:
      - fast-db
    networks:
      - rabbits

  fast-db:
    build:
      context: ./pg_db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgresql
    ports:
      - 35432:5432
    networks:
      - rabbits

networks:
  rabbits:
    external:
      name: rabbits
