version: '3.8'
services:
  backend:
    image: app_f
    command: gunicorn -w 2 -b 0.0.0.0:5000 main:app
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db_u
    networks:
      - rabbits

  queue_f:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_f
    command: python -u consumer.py
    depends_on:
      - db_u
    networks:
      - rabbits

  db_u:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
    networks:
      - rabbits

networks:
  rabbits:
    external:
      name: rabbits
