version: '3.8'
services:
  backend:
    image: app_f
    command: python main.py
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - rabbits

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_f
    command: python consumer.py
    depends_on:
      - db
    networks:
      - rabbits

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
    networks:
      - rabbits

networks:
  rabbits:
    external: true
    name: rabbits
